export const FETCH_RATES = "FETCH_RATES";
export const FETCH_HISTORY_WORTHS = "FETC_HISTORY_WORTHS";
export const SELECT_BASE_RATE = "SELECT_BASE_RATE";
export const SET_SECONDARY_RATES = "SET_SECONDARY_RATES";
